Map<String, dynamic> lan = {
  "discoverthebestgoods":
      "Discover the best goods from over 1,000 shops and fast delivery to your doorstep",
  "intro":
      "Harkat Shop is a good ordering platform that provide services to connect shops (owners of goods) with the interested customers with the option of delivery to the selected items.",
  "detailtologin": "Add your details to log in",
  "loginasgest": "Login as Guest",
  "loginwith": "Login With",
  "loginwithfb": "Login With Facebook",
  "loginwithgoogle": "Login With Google",
  "resetpassword": "Reset Password",
  "pleaseenteremailtorecoverpass":
      "Please enter your email to recover password",
  "addyourdeatiltosignin": "Add your details to sign up",
  "mobilenumber": "Mobile no",
  "address": "Address",
  "conformpassword": "Confirm Password",
  "alreadyhaveacc": "Already have an Account?",
  "findgoodsforyou": "Find Good's You Love",
  "discoverthebestgoodsfromovermany":
      "Discover the best goods from over many shops and fast delivery to your doorstep",
  "fastdelivery": "Fast Delivery",
  "fastfooddeliverytoyourhome":
      "Fast food delivery to your home, office wherever you are",
  "livetracking": "Live Tracking",
  "realtimetrackingofyourfood":
      "Real time tracking of your food on the app once you placed the order",
  "welcome": "Welcome",
  "deliveringto": "Delivering to",
  "currentlocation": "Current Location",
  "searchitems": "search items",
  "popularshops": "Popular Shopes",
  "viewall": "View all",
  "rating": "ratings",
  "mostpopular": "Most Popular",
  "recentitem": "Recent Items",
  "menu": "Menu",
  "foodcategory": "Food Category",
  "latestoffers": "Latest Offers",
  "finddiscounts": "Find discounts, Offers special meals and more!",
  "checkOffers": "Check Offers",
  "profile": "Profile",
  "editprofile": "Edit Profile",
  "hiuser": "Hi There User!",
  "signout": "Sign Out",
  "mrxyz": "Mr xyz",
  "required": "required",
  "require": "this field is required",
  "cannotbeempty": "this field can't be empty",
  "eamilsample": "saeed@gmail.com",
  "numsample": "+92304687892455",
  "addresssample": "No 23, 6th Al Nehyan Camp, Abu Dhabi",
  "dobsample": "DOB : 12/10/2022",
  "gender": "Gender",
  "password": "Password",
  "message": "message",
  "fazza": "Fazaa",
  "isaad": "Isaad",
  "humatalwatan": "Humat Al Watan",
  "more": "More",
  "paymetdetail": "Paymet Detail",
  "myorder": "My Order",
  "notification": "Notification",
  "inbox": "Inbox",
  "aboutus": "About Us",
  "customizeyourpayment": "Customize your payment method",
  "addanothercredit": "Add Another Credit/Debit Card",
  "addnote": "Add Notes",
  "deliveryinstrusctions": "Delivery Instrusctions",
  "checkout": "Check Out",
  "subtotal": "Sub Total",
  "total": "Total",
  "checkhout": "Check Out",
  "deliveryaddress": "Delivery Address",
  "change": "Change",
  "paymetmethod": "Payment method",
  "addcard": "Add Card",
  "cashondelivery": "Cash on delivery",
  "cardnumersample": "Card **** **** **** 2187",
  "deliverycost": "Delivery Cost",
  "discount": "Discount",
  "sendorder": "Send Order",
  "thankyou": "Thank You",
  "foryourorder": "for your order",
  "trackmyorder": "Track my order",
  "backtohome": "Back to home",
  "perunit": "per unit",
  "description": "Description",
  "numberofportios": "Number of Portions",
  "customizeyourorder": "Customize your Order",
  "addtocartsuccessfuly": "Add To Cart Sucessfully",
  "addtocart": "Add To Cart",
  "error": "Rrror",
  "sucess": "Sucess",
  "login": "Login",
  "signup": "Sign Up",
  "create": "Create",
};
